version: '3.3'
services:
  db:
    image: 'mariadb'
    volumes:
        - db_data:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: heticwp_marmiton
        MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
  wordpress:
    depends_on:
        - db
    image: wordpress:latest
    ports:
        - "8000:80"
    volumes:
      - .:/var/www/html/wp-content
    restart: always
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: password
        WORDPRESS_DB_NAME: heticwp_marmiton
volumes:
  db_data: {}